# Generated by Django 3.2.5 on 2021-08-04 16:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Product', '0006_alter_product_options'),
        ('Organization', '0004_alter_followup_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='کاربر ثبت کننده')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Organization.organization', verbose_name='سازمان')),
            ],
            options={
                'verbose_name': 'پیش فاکتور',
                'verbose_name_plural': 'پیش فاکتور ها',
            },
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='قیمت')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='تعداد')),
                ('discount', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='درصد تخفیف')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Product.product', verbose_name='محصول')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quote.quote', verbose_name='پیش فاکتور')),
            ],
            options={
                'verbose_name': 'رکورد پیش فاکتور',
                'verbose_name_plural': 'رکورد پیش فاکتورها',
            },
        ),
    ]
