# Generated by Django 3.2.5 on 2021-08-04 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0003_alter_organizationproduct_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='followup',
            unique_together=set(),
        ),
    ]
