# Generated by Django 3.2.5 on 2021-08-03 11:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_rename_name_product_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to='Product/PDFs', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='کاتولوگ محصول'),
        ),
    ]
