# Generated by Django 3.2.5 on 2021-08-04 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_alter_product_pdf_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
    ]
